#!/bin/bash

formatTime () {
	d=$(TZ="$1" date -d "+$2 hours" +"%d-%m-%Y")
	TIME="$(TZ="$1" date -d "+$2 hours" +"%I:%M %p")"
	echo "$1\n$d\n$TIME"
}

actions=(
	-kb-custom-1 "KP_Add"
	-kb-custom-2 "KP_Subtract"
)


hours=0

while true; do
	options="$(formatTime "US/Pacific" "$hours")_$(formatTime UTC "$hours")_$(formatTime "Asia/Kolkata" "$hours")"

	echo -e "$options"| rofi -p "$(TZ="Asia/Kolkata" date +"%I:%M %p")" -dmenu -theme "~/.config/rofi/theme.rasi" -sep "_" -selected-row 1 "${actions[@]}"
	reponse=$?

	case "$reponse" in
	    10) echo "10";hours=`expr $hours + 1`;;
	    11) echo "11";hours=`expr $hours - 1`;;
	    *) echo "exit"; exit "$?";;
	esac
done
